### ISSUE TITLE
Manage server.properties endpoints

### ISSUE THREAD

**Issue by johnbwoodruff** [open-realms/express-minecraft#3]
* `GET` /properties - Should parse `server.properties` file and return as a JSON object
* `PUT` /properties - Should accept a JSON object and update all values in the `server.properties` file

Notes: Can use https://github.com/strugee/node-minecraft-server-properties/blob/dev/index.js as an example

**Comment by andrewgwoodruff** [comment]
These endpoints have been added, so I'm closing the issue.
